### ISSUE TITLE
Extract Importer class as a dependency of InMemoryConferencesRepository

### ISSUE THREAD

**Issue by mfedkowicz** [NetworkedCoders/speech-rank#40]
Right now `Importer` class instance is created inside `InMemoryConferencesRepository` constructor. This design choice makes testing `InMemoryConferencesRepository` impossible without using dirty hacks. It would be nice to extract it as a dependency injected in the constructor. Such a change would allow to easily mock `Importer` and avoiding hitting YT API in future `ConferencesRepository` tests.

**Comment by jansowa** [comment]
https://github.com/jansowa/speech-rank/tree/%2333
Work in progress

**Comment by BarteKKmita** [comment]
I will take that.

**Comment by mfedkowicz** [comment]
implemented in https://github.com/NetworkedCoders/speech-rank/pull/43
